config/routes.rb
Rails.application.routes.draw do
  
  root 'chatroom#index'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  scope :custom_display, -> { all.includes(:user).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, length: { minimum: 5, maximum: 15 }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    valido = params[:valido].present? || message.body == 'sim'
    if valido && message.save 
      ActionCable.server.broadcast "chatroom_channel",
      mod_message: message_render(message)
    else
      render 'update', locals: { body: message.body, message: message_params }
    end
  end

  def update

  end

  private
  
  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :loggin_in_redirect, only: %i[new create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else 
      flash.now[:error] = 'There wass something wrong with you login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  def loggin_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular green coffee icon"></i>
  Say something
</h2>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted green edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

<div id="teste"></div>

app/views/layouts/_menu.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: "item" %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
          <% else %>
            <%= link_to "Login", login_path, class: "item" %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition" >
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/menu'%>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>:
      <%= message.body %>
    </div>
  </div>
</div>

app/views/messages/_mostra_partial.html.erb
<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">
    Profile Picture
  </div>
  <div class="image content">
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="https://www.gravatar.com" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
      <h4><%= body %></h4>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      Nope
    </div>
    <%= link_to message_path(valido: 'true', message: message), method: :post, remote: :true do %>
      <div class="ui positive right labeled icon button">
        Yep, thats me
        <i class="checkmark icon"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/update.js.erb
$('.modals').remove() //limpa os ocultos
$('#teste').html("<%= j render :partial => 'mostra_partial', locals: {body: body, message: message} %>");
$('.ui.modal')
  .modal('show')
;

app/views/session/new.html.erb
<h2 class="ui center aligned medium icon header">
  <p>Welcome to MessageMe</p>
  <i class="circular green coffee icon"></i>
  Login to continue
</h2>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Username" %>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder: "Password" %>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui green submit button" %>
      <% end %> 
    </div>
    <div class="middle aligned column">
      <div class="ui big green button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>